version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  go:
    build: ./
    command: ./linkshorteningservice
    ports:
      - 8001:8001
    depends_on:
      - db

