version: '3.8'

services:
  linkshorteningservice:
    build: ./
    command: ./linkshorteningservice
    ports:
      - 8001:8001
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
