version: '3.8'

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
       - dbdata:/var/lib/postgresql/data
  go:
    container_name: go
    ports:
      - "8001:8001"
    build:
      context: .
    depends_on:
      - "db"

volumes:
  dbdata:
